apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pagesuccess-cj
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pagesuccess-cj
            image: tbsacr.azurecr.io/pagesuccess-cj:1.0.0
            imagePullPolicy: Always
            resources: 
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 500m
                memory: 256Mi
            args:
            - java
            - -jar 
            - app.jar
          restartPolicy: OnFailure