# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none  

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'
- bash: |
    az login \
        --service-principal \
        -u $(aksSpId) \
        -p $(aksSpSecret) \
        --tenant $(aksSpTenantId)
    az aks get-credentials \
        -n $(aks) \
        -g $(rg)
    kubectl create namespace $(instanceName)
    helm install \
        $(instanceName) \
        -f ./helm-drupal/drupal/$(helmValues) \
        --namespace $(instanceName) \
        --wait \
        --timeout 30m \
        ./helm-drupal/drupal
  failOnStderr: true
  displayName: 'login to azure'

