apiVersion: v1
data:
  nginx.conf: |
    error_log /proc/self/fd/2;
    pid /var/run/nginx.pid;
    user nginx;
    worker_processes auto;
    worker_rlimit_nofile 100000;

    events {
      multi_accept on;
      use epoll;
      worker_connections 8192;
    }

    http {
      access_log /proc/self/fd/1;
      client_max_body_size 20m;
      default_type application/octet-stream;
      gzip on;
      gzip_buffers 16 8k;
      gzip_comp_level 4;
      gzip_disable msie6;
      gzip_proxied off;
      gzip_types application/json;
      gzip_vary on;
      #include /etc/nginx/mime.types;
      index index.html index.htm;
      keepalive_timeout 120;
      proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=one:8m max_size=3000m inactive=600m;
      proxy_temp_path /var/tmp;
      sendfile on;
      server_tokens off;
      tcp_nopush on;
      types_hash_max_size 2048;

      server {
          #IPv4
          listen 80;

          #IPv6
          listen [::]:80;

          location / {
            autoindex on;
            proxy_hide_header "Cache-Control";
            proxy_hide_header "Strict-Transport-Security";
            add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
            proxy_hide_header "Pragma";
            add_header Pragma "no-cache";
            expires -1;
            add_header Last-Modified $sent_http_Expires;
            proxy_redirect off;
            proxy_pass https://design-system-systeme-conception.netlify.com;
          }
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"nginx.conf":"error_log /proc/self/fd/2;\npid /var/run/nginx.pid;\nuser nginx;\nworker_processes auto;\nworker_rlimit_nofile 100000;\n\nevents {\n  multi_accept on;\n  use epoll;\n  worker_connections 8192;\n}\n\nhttp {\n  access_log /proc/self/fd/1;\n  client_max_body_size 20m;\n  default_type application/octet-stream;\n  gzip on;\n  gzip_buffers 16 8k;\n  gzip_comp_level 4;\n  gzip_disable msie6;\n  gzip_proxied off;\n  gzip_types application/json;\n  gzip_vary on;\n  #include /etc/nginx/mime.types;\n  index index.html index.htm;\n  keepalive_timeout 120;\n  proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=one:8m max_size=3000m inactive=600m;\n  proxy_temp_path /var/tmp;\n  sendfile on;\n  server_tokens off;\n  tcp_nopush on;\n  types_hash_max_size 2048;\n\n  server {\n      #IPv4\n      listen 80;\n\n      #IPv6\n      listen [::]:80;\n\n      location / {\n        proxy_hide_header \"Cache-Control\";\n        proxy_hide_header \"Strict-Transport-Security\";\n        add_header Cache-Control \"no-store, no-cache, must-revalidate, post-check=0, pre-check=0\";\n        proxy_hide_header \"Pragma\";\n        add_header Pragma \"no-cache\";\n        expires -1;\n        add_header Last-Modified $sent_http_Expires;\n        proxy_redirect off;\n        proxy_pass https://design-system-systeme-conception.netlify.com;\n      }\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-en-conf","namespace":"proxy"}}
  creationTimestamp: "2020-02-10T19:29:25Z"
  name: nginx-en-conf
  namespace: proxy
  resourceVersion: "6392682"
  selfLink: /api/v1/namespaces/proxy/configmaps/nginx-en-conf
  uid: f051ebe8-54e6-4377-90a8-8fcd1c9b5969
