{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "indexer.serviceAccountName" . }}
  labels:
{{ include "indexer.labels" . | indent 4 }}
{{- end -}}
