version: '3.3'
services:
  solr:
    image: "ryanhyma/solr:latest"
    ports:
     - "8983:8983"
    volumes:
     - data:/opt/solr/server/solr/opt
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - opt
    build:
      context: .
      dockerfile: solr/Dockerfile
   
