{{- if eq .Values.files.provider "s3" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drupal.fullname" . }}-s3
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  accesskey: {{ .Values.s3.accessKey | b64enc | quote }}
  secretkey: {{ .Values.s3.secretKey | b64enc | quote }}
{{- end }}
