doapiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3"},"generation":1,"name":"pageperformance-nginx","namespace":"pageperformance"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"tier":"frontend"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"tier":"frontend"}},"spec":{"containers":[{"image":"tbsacr.azurecr.io/pageperformance_nginx:1.0.0","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/_healthz","port":80,"scheme":"HTTP"},"initialDelaySeconds":1,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"name":"nginx","ports":[{"containerPort":80,"name":"http","protocol":"TCP"},{"containerPort":443,"name":"https","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/_healthz","port":80,"scheme":"HTTP"},"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"cpu":"400m","memory":"500Mi"},"requests":{"cpu":"250m","memory":"200Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/etc/nginx/nginx.conf","name":"cm-nginx","readOnly":true,"subPath":"nginx.conf"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":33},"terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"name":"pageperformance-nginx"},"name":"cm-nginx"}]}}}}
  creationTimestamp: "2020-03-25T22:52:32Z"
  generation: 10
  labels:
    tier: frontend
  name: pageperformance-nginx
  namespace: pageperformance
  resourceVersion: "32073334"
  selfLink: /apis/extensions/v1beta1/namespaces/pageperformance/deployments/pageperformance-nginx
  uid: 1cbb01e8-04b1-4162-8798-1e62712ccf8c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2020-05-25T12:06:43-04:00"
      creationTimestamp: null
      labels:
        tier: frontend
    spec:
      containers:
      - image: tbsacr.azurecr.io/pageperformance_nginx:1.0.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /_healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /_healthz
            port: 80
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 400m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: cm-nginx
          readOnly: true
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 33
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: pageperformance-nginx
        name: cm-nginx
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-25T23:17:30Z"
    lastUpdateTime: "2020-05-25T16:06:48Z"
    message: ReplicaSet "pageperformance-nginx-7558d6d7fb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-05-25T17:38:12Z"
    lastUpdateTime: "2020-05-25T17:38:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
