#!/bin/bash
#
# Run the indexer java class and data file arguments
set -e

if [[ "$VERBOSE" == "yes" ]]; then
    set -x
fi

# Run the indexing from the java jar and their classes
java -version

echo $SOLR_URL
echo ${SPATH}


java -Dfile.encoding=UTF8 -classpath "${SPATH}/${ZNAME}/lib/*:${SPATH}/${ZNAME}/classes" com.norconex.collector.http.HttpCollector -a resume -c /opt/indexer-configs/canada-collector.xml -k -v /opt/indexer-configs/canada-collector-prod.variables



