apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: testbed-indexer-canada
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: testbed-indexer-canada
            image: ryanhyma/testbed_indexer:1.0.0
            command: ["indexer-run-canada"]
            imagePullPolicy: Always
            volumeMounts:
              - name: cron-vol
                mountPath: /opt/indexer-data
            resources: 
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 500m
                memory: 512Mi
          restartPolicy: OnFailure
          volumes:
            - name: cron-vol
              persistentVolumeClaim:
                claimName: indexer-pv-claim
          securityContext:
           runAsUser: 8080
           runAsGroup: 8080
           fsGroup: 8080
          
                
          
