apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: testbed-indexer
spec:
  schedule: "30 9 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: testbed-indexer
            image: ryanhyma/testbed_indexer:1.0.0
            imagePullPolicy: Always
            resources: 
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 500m
                memory: 512Mi
          restartPolicy: OnFailure
