apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: testbed-indexer-canada
spec:
  schedule: "0 23 */2 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: testbed-indexer-canada
            image: ryanhyma/testbed_indexer:1.0.0
            command: ["indexer-run-canada"]
            imagePullPolicy: Always
          restartPolicy: OnFailure
