version: "3"
services:
  nginx:
    image: "tbsacr.azurecr.io/pageperformance_nginx:1.0.0"
    build:
      context: .
      dockerfile: docker/images/pageperformance_nginx/Dockerfile
    ports:
      - "8181:80"
    depends_on:
      - web
    restart: always
    container_name: pageperformance_nginx
  web:
    image: "tbsacr.azurecr.io/pageperformance_php:1.0.0"
    build:
      context: .
      dockerfile: docker/images/pageperformance_php/Dockerfile
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
    environment:
      - DRUPAL_SETTINGS=development
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
    ports:
      - "9000"
    container_name: pageperformance_web
volumes:
  dbdataold:
