apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.beta.kubernetes.io/gid: "8983"
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
  creationTimestamp: "2020-04-28T20:40:02Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: solr
    release: testbed-solr
  name: data-testbed-solr-0
  namespace: testbed
  resourceVersion: "25076695"
  selfLink: /api/v1/namespaces/testbed/persistentvolumeclaims/data-testbed-solr-0
  uid: 191fac6d-d88b-4c45-9773-ff7b6e389e14
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: default
  volumeMode: Filesystem
  volumeName: pvc-191fac6d-d88b-4c45-9773-ff7b6e389e14
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  phase: Bound
