apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-01-08T16:53:20Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: drupal
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: drupal
    helm.sh/chart: drupal-0.1.7
  name: drupal-nginx
  namespace: drupal
  resourceVersion: "129323"
  selfLink: /apis/extensions/v1beta1/namespaces/drupal/deployments/drupal-nginx
  uid: 56f0db74-7c46-4ecf-ae45-b2734751460a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: drupal
      app.kubernetes.io/name: drupal
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: drupal
        app.kubernetes.io/name: drupal
        tier: frontend
    spec:
      containers:
      - image: drupalwxt/site-wxt:3.0.1-nginx
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /_healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /_healthz
            port: 80
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 400m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: cm-nginx
          readOnly: true
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 33
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: drupal-nginx
        name: cm-nginx
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-08T16:53:20Z"
    lastUpdateTime: "2020-01-08T16:53:25Z"
    message: ReplicaSet "drupal-nginx-65457fd4c4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-01-08T19:55:34Z"
    lastUpdateTime: "2020-01-08T19:55:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
