apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-fr-conf
data:
  nginx.conf: |
    error_log /proc/self/fd/2;
    pid /var/run/nginx.pid;
    user nginx;
    worker_processes auto;
    worker_rlimit_nofile 100000;

    events {
      multi_accept on;
      use epoll;
      worker_connections 8192;
    }

    http {
      access_log /proc/self/fd/1;
      client_max_body_size 20m;
      default_type application/octet-stream;
      gzip on;
      gzip_buffers 16 8k;
      gzip_comp_level 4;
      gzip_disable msie6;
      gzip_proxied off;
      gzip_types application/json;
      gzip_vary on;
      #include /etc/nginx/mime.types;
      index index.html index.htm;
      keepalive_timeout 120;
      proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=one:8m max_size=3000m inactive=600m;
      proxy_temp_path /var/tmp;
      sendfile on;
      server_tokens off;
      tcp_nopush on;
      types_hash_max_size 2048;

      server {
          #IPv4
          listen 80;

          #IPv6
          listen [::]:80;

          location / {
            #proxy_hide_header "Cache-Control";
            #proxy_hide_header "Strict-Transport-Security";
            #add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
            #proxy_hide_header "Pragma";
            #add_header Pragma "no-cache";
            #expires -1;
            #add_header Last-Modified $sent_http_Expires;
            #proxy_redirect off;
            #proxy_pass https://www.canada.ca/en/government/about/design-system.html;
            return 302 https://www.canada.ca/fr/gouvernement/a-propos/systeme-conception.html;
          }
      }
    }
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-fr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: nginx-fr-conf
      volumes:
      - name: nginx-fr-conf
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-fr
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx