apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-25T23:31:09Z"
  labels:
    tier: frontend
  name: pageperformance-nginx
  namespace: pageperformance
spec:
  clusterIP: 10.0.252.175
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    tier: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
