apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: abjs-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: abjs-drupal.alpha.experimentation.ca
    http:
      paths:
      - backend:
          serviceName: abjs-drupal-nginx
          servicePort: 80
        path: /
      