apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pageperformance-alpha-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - pageperformance.alpha.canada.ca
    secretName: covid19inv-tls-secret-prod
  rules:
  - host: pageperformance.alpha.canada.ca
    http:
      paths:
      - backend:
          serviceName: pageperformance-nginx
          servicePort: 80
        path: /
      