apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: pageperformance
  name: pageperformance-alpha-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 3000s
    nginx.ingress.kubernetes.io/proxy-send-timeout: 3000s
    nginx.ingress.kubernetes.io/proxy-read-timeout: 3000s
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: 3000s
    nginx.ingress.kubernetes.io/client-header-timeout: 3000s
spec:
  tls:
  - hosts:
    - pageperformance.alpha.canada.ca
    secretName: covid19inv-tls-secret-prod
  rules:
  - host: pageperformance.alpha.canada.ca
    http:
      paths:
      - backend:
          serviceName: pageperformance-nginx
          servicePort: 80
        path: /
      