apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drupal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  settings.php: |
{{- if eq "d8" .Values.drupal.version }}
{{ tpl (.Files.Get "conf/settings.d8.php") . | indent 4 }}

{{- else }}
  settings.php:
    <?php

    // Unknown drupal version specified.
{{- end }}

{{- if .Values.drupal.extraSettings }}
  extra.settings.php:
    <?php

    {{- toYaml .Values.drupal.extraSettings | nindent 4}}
{{- end }}
