version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
    - 27017:27017
    volumes:
    - mongodb_data_container:/data/db
  pagesuccess:
    build: .
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    ports:
    - 9090:9090
    command: mvn -X clean spring-boot:run
    depends_on:
    - mongodb
volumes:
  mongodb_data_container: