#!/bin/bash
#
# Run the indexer java class and data file arguments
set -e

if [[ "$VERBOSE" == "yes" ]]; then
    set -x
fi

# Run the indexing from the java jar and their classes
java -version

echo ${SPATH}

# Command to run Solr and keep the verbose logs so the docker remains running
solr start -f -p 8983 -m 3000M
